### ISSUE TITLE
Signing in fails with 403 when using the extension

### ISSUE THREAD

**Issue by michel-zimmer** [gladly-team/tab-extensions#10]
When trying to sign in I get a 403 `CSRF verification failed` response. Everything is working fine when visiting [https://tab.gladly.io/newtab/](https://tab.gladly.io/newtab/). I'm using the email + password method.

Screenshot when using the extension:
![screenshot_20171205_123806](https://user-images.githubusercontent.com/4385736/33615107-8413522e-d9d9-11e7-8dfb-7ae1163778f4.png)

Screenshot when visiting the new tab page directly:
![screenshot_20171205_123815](https://user-images.githubusercontent.com/4385736/33615118-89650bf0-d9d9-11e7-8049-d8111de4c89d.png)

**Comment by kmjennison** [comment]
Thanks for reporting the issue. I'm having trouble reproducing it, so I have a few questions:
* Do you see this error when you visit https://tab.gladly.io/newtab/ directly? (I expect this will redirect to /tab/: we're in the middle of migrating users to the newest version of Tab for a Cause, and your screenshot is of the new version.)
* Are you restricting cookies, using private/incognito browsing, or using any privacy/adblocking browser extensions?
* Does clearing your cookies for tab.gladly.io affect the issue?
* What's your Tab for a Cause username? (If you don't feel comfortable sharing here, feel free to email it to contact@tabforacause.org).

**Comment by michel-zimmer** [comment]
The cookies were the problem. For some reason tab.gladly.io was not in the list of exceptions anymore. I've added it again and it's working as expected now. Maybe there could be a note to allow cookies when signing in or so.

**Comment by kmjennison** [comment]
Glad to hear it, thanks. This will not be a problem after we're finished completely migrating to the new version, because it doesn't rely on cookies.
