### ISSUE TITLE
Firefox doesn't display TabForACause extension page when first launched

### ISSUE THREAD

**Issue by CorneliaXaos** [gladly-team/tab-extensions#16]
When Firefox is launched for the first time, the page contains Firefox's "New Tab" page instead of the TabForACause page.  This can (sorta) be worked around by setting the on-launch page to be the url https://tab.gladly.io/newtab/

This, however, has the problem that the address bar will contain a URL and makes quick usage difficult.  Is there a way to make it so that the extension overrides the launch page as well?

**Comment by kmjennison** [comment]
Thanks for the issue! Unfortunately, I don't think Firefox currently allows this. Firefox extensions can only override the new tab page, not the launch/homepage. I tried setting the homepage to `about:newtab` in Firefox preferences, but that just displays the default Firefox new tab page, not Tab for a Cause (contrary to Chrome, where `chrome://newtab` will display the Tab for a Cause page).

If this becomes available in the future, we'll make it happen.
