### ISSUE TITLE
Make extension icon action open a new tab page

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/tab-extensions#17]

**Comment by blue-putty** [comment]
Is this still open? I'd love to work on this.

**Comment by kmjennison** [comment]
@blue-putty Yes, feel free to. Thanks!

**Comment by blue-putty** [comment]
@kmjennison 
Currently, the Edge extension is on Manifest V2, which uses chrome.browserAction to handle icon action events. However, this was changed to chrome.action in Manifest V3, which is what the Chrome extension is on. Should I update the jest configuration to concurrently include the browserAction and action properties or change the Edge extension to Manifest V3?

**Comment by kmjennison** [comment]
@blue-putty If you'd like to open a PR to first update the Edge manifest to v3, that's welcome! If not, go ahead and use `chrome.browserAction`, and we'll update the API later when we update the manifest version. Thanks!

**Comment by blue-putty** [comment]
@kmjennison Thanks! I've opened #40 for the Edge manifest update.
